version: '3'

networks:
  alert_bot_network:
    external: true

services:
  alert_bot:
    image: alert_bot:latest
    container_name: alert_bot
    build: .
    env_file:
      - ./environments/prod.env
    volumes:
      - /docker/data/alert_bot:/data
    networks:
      - alert_bot_network
    restart: unless-stopped
